### ISSUE TITLE
Plugin not works properly on Mobile (iOS/Android)

### ISSUE THREAD

**Issue by AlexeyBuzdin** [sampaiodiego/rocket.chat.app-poll#11]
Hi Diego, first of all, thank you very much for writing the plugin!

Have you had a chance to test it in Rocket Chat Mobile apps?
- For us Android RC 3.2.0 poll shows correctly, but voting does not work.
- For iOS the poll is not rendered correctly at all

Do you know a possible root cause for this? I'll try to analyze it myself, maybe I will find a root cause

**Comment by sampaiodiego** [comment]
Thank you @AlexeyBuzdin for reporting =)

Seems mobile apps doesn't support this elements. I'll open an issue in both mobile repos so we can track it. I'll update this issue accordingly

**Comment by AlexeyBuzdin** [comment]
Thanks. Appreciate the effort!

**Comment by lorek123** [comment]
@sampaiodiego Can you post those issue links here? I'd love to hear more about them.

**Comment by sampaiodiego** [comment]
sorry the delay guys.. I have created the following issues:
https://github.com/RocketChat/Rocket.Chat.iOS/issues/2565
https://github.com/RocketChat/Rocket.Chat.Android/issues/2036
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/649
