### ISSUE TITLE
Replace the avatar URL for poll with a local image

### ISSUE THREAD

**Issue by magenbrot** [sampaiodiego/rocket.chat.app-poll#17]
Hi, 

can you change the Poll Avatar image (configured here: https://github.com/sampaiodiego/rocket.chat.app-poll/blob/1db78abc13ce391526f3b74d6152fded6203faf9/src/PollCommand.ts#L33 ) to a locally hosted version and bundle the image within the release?

Would be great for my paranoid colleagues or for an rocket.chat instance without access to the internet for example.

Best regards
Oli

**Comment by sampaiodiego** [comment]
Right, makes sense.. Thanks for suggesting, I'll see what can be done.
