### ISSUE TITLE
Can't see all voters name after certain count

### ISSUE THREAD

**Issue by hupptechnologies** [sampaiodiego/rocket.chat.app-poll#20]
When we are voting with 15+ people in group - if there are many votes on any particular option 
The message on hover shows initial 10-12 users name and then ends like e.g. `and 14 more`
is there a way to see those other `14` users ?

**Comment by sampaiodiego** [comment]
what the app version are you using? looks like you are using pre v1 which uses reactions to vote.

**Comment by sampaiodiego** [comment]
closing per lack of response..

please let me know if the issue still happens on the latest version of the app
