### ISSUE TITLE
HOWTO: Install guide.

### ISSUE THREAD

**Issue by feltra** [sampaiodiego/rocket.chat.app-poll#21]
What steps should I follow to install it ?

**Comment by feltra** [comment]
Nerver mind I see now there is a market place

**Comment by sampaiodiego** [comment]
Awesome.. I might add that information to the README still.

Once the marketplace have direct links to apps, I'll add it too.

**Comment by feltra** [comment]
Is there a way to install it manually ?

**Comment by sampaiodiego** [comment]
I might need to developer guides as well =)

so you'll need Rocket.Chat Apps cli:
```
npm install -g @rocket.chat/apps-cli
```

you'll also need to enable development mode for Rocket.Chat Apps on your Rocket.Chat administration page, General menu under Apps section:
![image](https://user-images.githubusercontent.com/8591547/68390327-cc491680-0143-11ea-8bf1-fb2c03009c3d.png)


then you can deploy it running this command from root folder of this repo:
