### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mrychu** [sampaiodiego/rocket.chat.app-poll#22]
Hi, can you add some instructions how to install this in rocketchat?

**Comment by sampaiodiego** [comment]
Yes.. in the mean time, the preferred way is install via Rocket.Chat Marketplace (from admin area).. to install in development mode you'll need [rc-apps cli](https://github.com/RocketChat/Rocket.Chat.Apps-cli/), then:
```
npm i
rc-apps deploy

**Comment by sampaiodiego** [comment]
Done.. please let me know if that answers your question.

**Comment by sampaiodiego** [comment]
Installing - https://github.com/sampaiodiego/rocket.chat.app-poll#installing
Contributing - https://github.com/sampaiodiego/rocket.chat.app-poll#contributing
