### ISSUE TITLE
Use name instead of username attribute to display voters

### ISSUE THREAD

**Issue by PatriceG** [sampaiodiego/rocket.chat.app-poll#24]
Hi,
We're using this extension and it's cool but it displays our cryptic usernames instead of the real names of the voters.
It would be nice if this extension could display either the name or username via a parameter.

It doesn't look very difficult but I'm not into TS/js development at all so hopefully someone else finds this usefull too and implements it :)

**Comment by sampaiodiego** [comment]
Definitely a nice improvement.

I wonder if that should be the default though..

**Comment by PatriceG** [comment]
I understand. 
I managed to patch it to display the name of the voters instead of the username (and remove the @ prefix). However I have no idea how to add configuration to a slash command so that it can work in either mode (username or name).

**Comment by sampaiodiego** [comment]
closed by #25
