### ISSUE TITLE
Unable to install 2.x

### ISSUE THREAD

**Issue by gabrielloberg** [sampaiodiego/rocket.chat.app-poll#32]
Hi,

I am unable to install version 2.x through the marketplace. The latest version there is 1.2.0.
Using Rocket.Chat 3.0.0

**Comment by sampaiodiego** [comment]
thanks for letting me know @gabrielloberg .. I'm already trying to find out why it was not published yet..

**Comment by sampaiodiego** [comment]
v2 is now published on marketplace.. 🎉  thanks again for the heads up
