### ISSUE TITLE
Not working on android

### ISSUE THREAD

**Issue by albebert** [sampaiodiego/rocket.chat.app-poll#34]
Hi,

voting is not possible on modile app : 

![Screenshot_20200227-170244](https://user-images.githubusercontent.com/1460379/75461881-aa3e0300-5983-11ea-9808-a734e7ff52fa.jpg)

as you can see the is no button in order to vote. you can't click on anything. 

tel me if you need anything 

tanks

**Comment by sampaiodiego** [comment]
hi @albebert .. the poll version you've installed is not supported on mobile apps. only v2 is supported and you need rocket.chat 3.0 to be able to install v2.

**Comment by albebert** [comment]
ok thanks
