### ISSUE TITLE
After 10 options, option numbers are "undefined"

### ISSUE THREAD

**Issue by FREEZX** [sampaiodiego/rocket.chat.app-poll#39]
After the 10th option, the number of the answer becomes undefined.
![Screen Shot 2020-03-11 at 09 27 11](https://user-images.githubusercontent.com/243900/76396988-937faf00-637a-11ea-94e9-a843958be3f9.png)

**Comment by sampaiodiego** [comment]
this is an issue with only the deprecated v1.x .. I'll make it clear that v1.x is currently deprecated.

please update to v2.x .. the whole app is way better =)
