### ISSUE TITLE
Command to end a poll

### ISSUE THREAD

**Issue by sampaiodiego** [sampaiodiego/rocket.chat.app-poll#4]
that app could have a `/poll end` command or having a "message action" to end it.

ending a poll would then prevent new votes and displaying the final result of the poll as a new message.

**Comment by sampaiodiego** [comment]
depends on https://github.com/RocketChat/Rocket.Chat/pull/11780

**Comment by lorek123** [comment]
@sampaiodiego the dependency is now resolved, could you add this feature now?

**Comment by colinmasters** [comment]
vote for this feature
