### ISSUE TITLE
i dont know why do you call it a polls when you can not vote for individual things ....

### ISSUE THREAD

**Issue by goors** [sampaiodiego/rocket.chat.app-poll#5]

**Comment by sampaiodiego** [comment]
I'll update the repo with some examples as soon I update the app to engine version 1.0.0

**Comment by sampaiodiego** [comment]
hopefully it got answered by the new readme.

**Comment by sampaiodiego** [comment]
you ask a question, give people some options, they vote using reactions. what makes a poll other than this?

**Comment by goors** [comment]
This thing is just a message with attachment (as any other message in rocket chat). Poll give you options to vote for individual stuff (1, 2, 3 and so on).

Lats say with your "poll" you got something like:

/poll "Your favourite food is?" "Pizza" "Big Mack" "Cheeseburger"

How do you vote for "Cheeseburger" or any other option? You can not!!! So I don't see how this is any different then voting (assigning emotions) for regular message?

**Comment by sampaiodiego** [comment]
> So I don't see how this is any different then voting (assigning emotions) for regular message?

it is not different. so do you think adding a reaction to a message is not the same as voting?
