### ISSUE TITLE
Confidential votes are displaying voters' names

### ISSUE THREAD

**Issue by n-kall** [sampaiodiego/rocket.chat.app-poll#51]
Rocket.Chat Version: 3.6.0-develop
Apps Engine Version: 1.16.0
Poll Version: 2.0.0

Confidential polls do not seem to work as intended, as when choosing 'confidential', the voters' usernames still appear just like in an 'open vote' poll.

To reproduce: create a poll and choose confidential, then add a vote, your name will appear and will be visible for all in the channel.

**Comment by sampaiodiego** [comment]
hi @n-kall .. this was actually fixed on rocket.chat side by the commit https://github.com/RocketChat/Rocket.Chat/commit/0e2309efc31275c02e7e05e75f056b7c266abdf5 and shipped on rocket.chat version 3.5.3 and 3.6.0 ..

seems you're running `3.6.0-develop` so you might be able to just update with a latest rocket.chat version and you should be fine.

**Comment by n-kall** [comment]
Thank you, updating rocket chat fixed it!
