### ISSUE TITLE
Poll: Create Button not working

### ISSUE THREAD

**Issue by wajeeh-devsinc** [sampaiodiego/rocket.chat.app-poll#53]
Cloned RC latest code from git repo, installed dependencies then poll app. Creating poll with /poll makes poll questionnaire pop up. After filling details, when I click on CREATE button, it's not creating the poll. Rather it takes the cursor to `Insert your question` field. Any fixes..?

**Comment by sampaiodiego** [comment]
have you tried create a poll in other rooms? does it fail to create as well?

I'm wondering if it can be the same issue as https://github.com/sampaiodiego/rocket.chat.app-poll/issues/46

**Comment by wajeeh-devsinc** [comment]
@sampaiodiego yeah have seen it. which permission I need to change..?

**Comment by wajeeh-devsinc** [comment]
Poll uses meesge APIs. That API was customized according to my nature of requirement. So the issue was with the customized API.
