### ISSUE TITLE
bug?  attention returns to question after typing a single character in option.

### ISSUE THREAD

**Issue by harmeling** [sampaiodiego/rocket.chat.app-poll#56]
First of thanks for the great tool /poll!
Here is the problem:
/poll thequestion
Then the window opens and the cursor is at the question. 
Either hitting Tab or clicking into any of the options.  Now comes the bug: after typing a single character, the attention goes back to the question field.  Afterwards it works with Tab and clicking.  Any idea, what could be wrong?

From: api/info:  {"version":"3.4.3","success":true}

**Comment by sampaiodiego** [comment]
hi @harmeling I'm sorry the delay. thanks for reporting it. although I was able to reproduce that on rocket.chat 3.4.3 it doesn't happen on latest version (3.9.0) anymore..

**Comment by harmeling** [comment]
ok!  thank you!
