### ISSUE TITLE
Manual install on 3.9.1 not working

### ISSUE THREAD

**Issue by omgold** [sampaiodiego/rocket.chat.app-poll#59]
When I download the release zip package and try to install it on my RC instance, the web interface reports the error:

`Invalid App package. Could not find the classFile (PollApp.js) file.`

Apparently it doesn't understand that the file is actually named PollApp.ts.

Is it possible to install the app manually? Any ideas?

**Comment by sampaiodiego** [comment]
I'm sorry the delay @omgold .. but now you can download the file `poll_2.0.0_compiled.zip` from the latest release at https://github.com/sampaiodiego/rocket.chat.app-poll/releases/tag/v2.0.0
