### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by danfelbm** [sampaiodiego/rocket.chat.app-poll#61]
Hello there,

I see some strings are hardcoded. Is there anyway to translate the app?

Regards

**Comment by sampaiodiego** [comment]
Unfortunately Rocket.Chat UI Kit doesn't support i18n elements.. I'll open an issue there and close this issue as duplicated of https://github.com/sampaiodiego/rocket.chat.app-poll/issues/42.. thx
