### ISSUE TITLE
Polls dont work in E2EE Channels

### ISSUE THREAD

**Issue by b90g** [sampaiodiego/rocket.chat.app-poll#67]
### Reproduce:
1. Activate E2EE in a private group chat
2. try to create a poll
### Expcted:
a Poll form opens
### Actual:
polls dont work in e2ee chats.
### Server:
RC 3.12.1

**Comment by RonLek** [comment]
Hey @b90g . I couldn't reproduce this issue. I'm able to create polls within groups (private rooms) with E2E enabled **without** any problems.

![chrome-capture (3)](https://user-images.githubusercontent.com/28918901/113727861-28d2ab80-9713-11eb-8c15-455e85469f3b.jpg)

Could you please elaborate over your issue or share the logs of what happens when you create a poll within a private E2E room? (accessible via Administration -> View Logs)

**Comment by l8com** [comment]
https://user-images.githubusercontent.com/14282757/113728825-b6ec6900-96f6-11eb-8665-58f304afd635.mov

When I use an E2E encrypted channel, a slash command would not raise the plugin but would simply be pasted as text (including the slash). It works from iOS but it doesn't work on my Mac (Big Sur), neither in Safari nor in the Client.

**Comment by b90g** [comment]
@RonLek where you alone in the "E2EE"-Groupchat?

**Comment by l8com** [comment]
> @RonLek where you alone in the "E2EE"-Groupchat?

I have the same when alone in a channel. Same on Windows (with Windows Client and Firefox and Edge). Other slash command such as /help or /leave have the problem.

**Comment by l8com** [comment]
btw: we run v2.0.0

**Comment by RonLek** [comment]
> @RonLek where you alone in the "E2EE"-Groupchat?
@b90g yes I was the only one in that room.

Updated my RC server from 3.12.0-develop to 3.14.0-develop and I was able to reproduce this issue.

**Comment by l8com** [comment]
Oh, it's new. Thanks for the news. Did you try other slash commands (/help or /leave)?

**Comment by RonLek** [comment]
Yes. I did. Getting the same issue. Looks like a problem within the RC server itself within the new update.

**Comment by l8com** [comment]
so the issue should entered be there? Would you transfer that?

**Comment by RonLek** [comment]
@l8com I think @b90g would need to close this one and open an issue [here](https://github.com/RocketChat/Rocket.Chat/issues) or [here](https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues). This isn't something specific to the Poll App.

**Comment by l8com** [comment]
Not specific to the Poll App, I agree. But why would it not happen in iOS when it is a server issue?

**Comment by b90g** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/21571
