### ISSUE TITLE
Cannot read property 'IUIKitInteractionHandler' of undefined

### ISSUE THREAD

**Issue by dinhhoai2103** [sampaiodiego/rocket.chat.app-poll#71]
![image](https://user-images.githubusercontent.com/64089642/119600830-0fe09f80-be12-11eb-97a2-e89e5563d15e.png)

**Comment by Tazeg** [comment]
Same here. Did you find a solution ?

**Comment by sampaiodiego** [comment]
looks like missing a `npm install`

**Comment by dinhhoai2103** [comment]
> Same here. Did you find a solution ?

update rocket.chat apps-engine newest version

**Comment by dinhhoai2103** [comment]
> Same here. Did you find a solution ?

update **package.json**

`{
    "devDependencies": {
        "@rocket.chat/apps-engine": "^1.20.0",
        "tslint": "^5.10.0",
        "typescript": "^2.9.1"
    },
    "dependencies": {
        "@types/node": "^12.12.7"
    }
}`
