### ISSUE TITLE
Can't create a poll

### ISSUE THREAD

**Issue by beloniki** [sampaiodiego/rocket.chat.app-poll#74]
Hi.

My attempts to create a poll are failing.

![image](https://user-images.githubusercontent.com/28544737/132006955-9aab9140-9e1b-4233-aafe-13bbc63c0f01.png)

RC version 3.18.0, Docker platform.

**Comment by sampaiodiego** [comment]
that's odd.. I'll probably take a look on how to provide better error messages to make it easier to debug.

can you pls provide additional info? 

- what kind of room were you trying to create a poll? private/public channel, DM, etc..
- what are your user roles? are you admin?
- looks like it opened the modal, you filled all the values and hit "create", is that right? can you share the values you filled in?

thanks in advance

**Comment by beloniki** [comment]
Of course!
I tried to create within direct, public channel of private group, public channel, conversation of private channel of private group.
Yes, My role is admin.
Yes, it was modal. I tried both: empty "/poll" command, and with a subject. Yes, I filled all all the fields, pressed the Create button, and nothing was happened.
<img width="610" alt="Снимок экрана 2021-09-03 в 17 39 01" src="https://user-images.githubusercontent.com/28544737/132024629-42896573-7555-447f-b248-a88f05d807d8.png">

It works well before upgrade RC to 3.18.0

**Comment by beloniki** [comment]
Hi

Version 3.18.1 comes with useful logging. I watched this:
```
server.js:204 System ➔ error Error sending message: Error: Not enough permission
    at validateMessage (app/lib/server/functions/sendMessage.js:151:10)
    at sendMessage (app/lib/server/functions/sendMessage.js:165:2)
    at executeSendMessage (app/lib/server/methods/sendMessage.js:79:10)
    at app/apps/server/bridges/messages.ts:25:23
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

So what permissions should I give to the poll user?

**Comment by beloniki** [comment]
Looks like I found it. The user needs to have an message-impersonate rights.

**Comment by sampaiodiego** [comment]
great.. thanks for letting us know @beloniki .. so the "app" role didn't have that permission? did you remove it by yourself? it should be there by default

**Comment by beloniki** [comment]
Yes, the permission were by default. I removed it by myself to use "app" role for custom integrations.

**Comment by sampaiodiego** [comment]
got it, thx.. I'll talk to RC team and see how we can improve reporting that error to the end user instead of silently fail
