### ISSUE TITLE
Automate add Emoji

### ISSUE THREAD

**Issue by ged-nn** [sampaiodiego/rocket.chat.app-poll#8]
Need automate add Emoji for user simple action.
If 1 answer - add Emoji :one: 
If 2 answer - add Emoji :one: :two:  
....

**Comment by vodkhang** [comment]
great idea. I still find this app hard to use

**Comment by sampaiodiego** [comment]
please take a look at https://github.com/sampaiodiego/rocket.chat.app-poll/pull/9#issuecomment-459180489 and let me know if that fixes the issue

**Comment by sampaiodiego** [comment]
closing as *I think* it's fixed already with the new voting style
